$accountName= "laaz203cosmosdb"
$acct = "laaz203blobs"
$adminLogin="ServerAdmin"
$adminPassword="Change!Me!Please"
$appInsightsName = "laaz203aisample"
$appName="laaz203bloblog"
$batchAcctName = "laaz203batchacct"
$clientId = $sp.appId
$clientSecret = $sp.password
$cluster = "akscluster"
$container = "images"
$containerName = "images"
$containerSasUrl = "https://$stgacct.blob.core.windows.net/logs?$sas"
$databaseName = "myDatabase"
$dbName="masking"
$end = $now.AddMinutes(5).ToString('yyyy-MM-ddTHH:mmZ')
$funcappdns = "209f0a2d.ngrok.io"
$key = $(az storage account keys list `
$kvname = "laaz203kvsecrets"
$location = "westus"
$now = [DateTime]::UtcNow
$order1json = Get-Content -Path order1.json
$package = "publish.zip"
$planname = "dockerhubdeployasp"
$planName="laaz203bloblog"
$poolName = "myPool"
$propsFile = "props.json"
$publishDir = "publish"
$queue = "incoming-orders"
$queueName = "toarchive"
$repourl = "https://github.com/Azure-Samples/php-docs-hello-world"
$resourceGroup = "appinsights"
$resourceGroupName = "cosmosdb"
$rg = "aksdemos"
$rgname = "rbacmsistg"
$rgName="sql"
$sampleweb = az webapp show `
$sas = az storage blob generate-sas `
$serviceName = "laaz203search"
$site = az webapp show -n $appName -g $resourceGroup --query "defaultHostName" -o tsv
$sp = az ad sp create-for-rbac `
$sp = az ad sp create-for-rbac --name $spname | ConvertFrom-Json
$sp = az ad sp create-for-rbac --name LaAz203WebSiteManager | ConvertFrom-Json
$spname = "LaAz203SampleWebAppPrincipal"
$spobjid = az ad sp show `
$start = $now.ToString('yyyy-MM-ddTHH:mmZ')
$stgacctid = az storage account show `
$stgacctkey = $(az storage account keys list `
$stgacct = "laaz203rbacmsistg"
$stgacct = "laaz20bloglogstg"
$stgAcctName = "laaz203lasa"
$storageid = $(az storage account show `
$subid = az account show --query "id" -o tsv
$sysid = az webapp identity assign `
$tenantid = az account show --query tenantId -o tsv
$today = Get-Date 
$tomorrow = $today.AddDays(1)
$viewerendpoint = "https://$funcappdns/api/updates"
$webappname = "laaz203samplewebapp"
$webappplanname = "laaz203samplewebappplan"
$webapprgname = "laaz203samplewebapprg"
