$key = $(az storage account keys list `
$sampleweb = az webapp show `
$sas = az storage blob generate-sas `
$sas = az storage container generate-sas `
$site = az webapp show -n $appName -g $resourceGroup --query "defaultHostName" -o tsv
$sp = az ad sp create-for-rbac `
$sp = az ad sp create-for-rbac --name $spname | ConvertFrom-Json
$sp = az ad sp create-for-rbac --name LaAz203WebSiteManager | ConvertFrom-Json
$spobjid = az ad sp show `
$stgacctid = az storage account show `
 $stgacctkey = $(az storage account keys list `
$stgacctkey = $(az storage account keys list `
$storageid = $(az storage account show `
$subid = az account show --query "id" -o tsv
$sysid = az webapp identity assign `
$tenantid = az account show `
$tenantid = az account show --query "tenantId" -o tsv
$tenantid = az account show --query tenantId -o tsv